language: java
dist: xenial
jdk:
  - openjdk8

script:
  - cd scripts
  - ./build.sh
  - cd ..

before_deploy:
  - tar czf RoboViz.tar.gz bin/

deploy:
  provider: releases
  api_key:
    secure: nM54n+YgSHV/HqJ882cF1pumzji/yD0HsNYwof+Yy+wS1l6wWEBXPp6mdIGuspr9IfByHyBe1ep11SBhteiSy73X96JsKp3WUpMBoeoyNey/Bgbh7qa3Yy/ikJj68Arjl1DdCOlKjp5JIPGtKsBHxT29qFMSltxtGQ6AwV8WJYo=
  file:
    - RoboViz.tar.gz
  skip_cleanup: true
  on:
    tags: true
